

development:
  adapter: postgresql
  database: abus_dev1
  username: test_usr_dev1
  password:  test_usr_dev1
  host: localhost
  port: 5432 


#test: &test
test:
  adapter: postgresql
  database: abus_test1
  username: test_usr_dev1
  password:  test_usr_dev1
  host: localhost
  port: 5432 

production:
  adapter: postgresql
  database: abus_prod1
  username: test_usr1
  password:  test_usr1
  host: localhost
  port: 5432 
  
#cucumber:
#  <<: *test